events {}

http {
    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        location /billing {
            proxy_pass http://billing:8080;
        }

        location /execution {
            proxy_pass http://execution:8080;
        }

        location /identity {
            proxy_pass http://identity:8080;
        }

        location /work-orders {
            proxy_pass http://work-orders:8080;
        }
    }
}